openapi: 3.1.0
info:
  title: Swagger JariyahMu - OpenAPI 3.1.0
  description: |-
    JariyahMu's API Specification
    Some useful links:
    - [JariyahMu repository](https://github.com/MirzaHilmi/JariyahMu)
    - [JariyahMu Grand Design](https://www.figma.com/file/i8vH72XjEuJAIOuQbq554z/JAMU-IBU?type=design&node-id=1-3&mode=design&t=Ggptr49h65rWjxa2-0)
  contact:
    email: exquisitemirza@student.ub.ac.id
  license:
    name: MIT
    url: https://github.com/MirzaHilmi/JariyahMu/blob/master/LICENSE
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v1
    description: Version 1
  - url: http://localhost:8080/api/v2
    description: Version 2
tags:
  - name: plant
    description: Everything about plants
  - name: social media
    description: Social Media operations
  - name: user
    description: Operations about user
paths:
  /auth/signup:
    post:
      tags:
        - user
      operationId: signupUser
      summary: New User Signing up
      description: Store new user and generate JSON Web Token
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                fullName:
                  description: User Full Name
                  type: string
                email:
                  description: User Email
                  type: string
                  format: email
                password:
                  description: User Password that should at least be 8 characters long
                  type: string
                  format: password
                  minLength: 8
                passwordConfirmation:
                  description: Repeated password from the `password` property
                  type: string
                  format: password
              example:
                fullName: John Smith Doe
                email: johndoe67@gmail.com
                password: 12345678
                passwordConfirmation: 12345678
              required:
                - fullName
                - email
                - password
                - passwordConfirmation
          application/json:
            schema:
              type: object
              properties:
                fullName:
                  description: User Full Name
                  type: string
                email:
                  description: User Email
                  type: string
                  format: email
                password:
                  description: User Password that should at least 8 characters long
                  type: string
                  format: password
                  minLength: 8
                passwordConfirmation:
                  description: Repeated password from the `password` property
                  type: string
                  format: password
              example:
                fullName: John Smith Doe
                email: johndoe67@gmail.com
                password: 12345678
                passwordConfirmation: 12345678
              required:
                - fullName
                - email
                - password
                - passwordConfirmation
      responses:
        "200":
          description: Success Sign up Request
          content:
            application/json:
              schema:
                type: object
                required:
                  - token
                properties:
                  token:
                    type: string
                    description: JSON Web Token generated from provided resource
                    example: |-
                      eyJhbGciOiJIUzI1N.eyJzdWIiOiIxMjM0NTY3ODkwIiw.SflKxwRJSMeKKF2QT4fwp
        "403":
          description: User already authenticated and JSON Web Token is still valid
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GeneralError"
              example:
                code: 403
                message: Action forbidden, already authenticated
  /auth/login:
    post:
      tags:
        - user
      operationId: userLogIn
      summary: User Logging in
      description: Validate Identity and Generate JSON Web Token
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                fullName:
                  description: User Full Name
                  type: string
                email:
                  description: User Email
                  type: string
                  format: email
                password:
                  description: User Password that should at least be 8 characters long
                  type: string
                  format: password
                  minLength: 8
                passwordConfirmation:
                  description: Repeated password from the `password` property
                  type: string
                  format: password
              example:
                fullName: John Smith Doe
                email: johndoe67@gmail.com
                password: 12345678
                passwordConfirmation: 12345678
              required:
                - fullName
                - email
                - password
                - passwordConfirmation
          application/json:
            schema:
              type: object
              properties:
                fullName:
                  description: User Full Name
                  type: string
                email:
                  description: User Email
                  type: string
                  format: email
                password:
                  description: User Password that should at least 8 characters long
                  type: string
                  format: password
                  minLength: 8
                passwordConfirmation:
                  description: Repeated password from the `password` property
                  type: string
                  format: password
              example:
                fullName: John Smith Doe
                email: johndoe67@gmail.com
                password: 12345678
                passwordConfirmation: 12345678
              required:
                - fullName
                - email
                - password
                - passwordConfirmation
      responses:
        "200":
          description: Success Sign up Request
          content:
            application/json:
              schema:
                type: object
                required:
                  - token
                properties:
                  token:
                    type: string
                    description: JSON Web Token generated from provided resource
                    example: |-
                      eyJhbGciOiJIUzI1N.eyJzdWIiOiIxMjM0NTY3ODkwIiw.SflKxwRJSMeKKF2QT4fwp
        "403":
          description: User already authenticated and JSON Web Token is still valid
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GeneralError"
              example:
                code: 403
                message: Action forbidden, already authenticated
components:
  schemas:
    GeneralError:
      type: object
      properties:
        code:
          type: integer
          description: HTTP Response Status Code for the Error
          format: int32
          example: [401]
        message:
          type: string
          description: |-
            The Error Response Message. 
            Defaults to the HTTP Response Status Code Message
          example: Unauthorized
        errors:
          type: array
          items:
            type: object
            properties:
              parameter:
                type: string
                description: The Parameter Name thats causing the Error
                example: passwordConfirmation
              message:
                type: string
                description: The Error Message of the corresponding Parameter
                example: Password Confirmation must be the same as the specified Password
    APIResponse:
      type: object
      properties:
        code:
          type: integer
          description: |-
            HTTP Response Status Code for the Response. 
            Ideally this schema will always be used for a Successful Request
          format: int32
          example: 200
        message:
          type: string
          description: |-
            The API Response Message. 
            Defaults to the HTTP Response Status Code Message
          example: Transaction Succeed
