openapi: 3.1.0
info:
  title: Swagger JariyahMu - OpenAPI 3.1.0
  description: |-
    JariyahMu's API Specification.
    Some useful links:
    - [JariyahMu repository](https://github.com/MirzaHilmi/JariyahMu)
    - [JariyahMu Grand Design](https://www.figma.com/file/i8vH72XjEuJAIOuQbq554z/JAMU-IBU?type=design&node-id=1-3&mode=design&t=Ggptr49h65rWjxa2-0)
  contact:
    email: exquisitemirza@student.ub.ac.id
  license:
    name: MIT
    url: https://github.com/MirzaHilmi/JariyahMu/blob/master/LICENSE
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v1
    description: Development server
tags:
  - name: authentication
    description: Authentication mechanisms and requirements for accessing the API
  - name: social-media
    description: Operations related to social media interactions and integrations
paths:
  /auth/signup:
    post:
      tags:
        - authentication
      operationId: signupUser
      summary: User Signing up
      description: Store new user and generate JSON Web Token
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                fullName:
                  description: User Full Name
                  type: string
                email:
                  description: User Email
                  type: string
                  format: email
                password:
                  description: User Password that should be at least 8 characters long
                  type: string
                  format: password
                  minLength: 8
                passwordConfirmation:
                  description: Repeated password from the `password` property
                  type: string
                  format: password
              example:
                fullName: John Smith Doe
                email: johndoe67@gmail.com
                password: 12345678
                passwordConfirmation: 12345678
              required:
                - fullName
                - email
                - password
                - passwordConfirmation
          application/json:
            schema:
              type: object
              properties:
                fullName:
                  description: User Full Name
                  type: string
                email:
                  description: User Email
                  type: string
                  format: email
                password:
                  description: User Password that should at least 8 characters long
                  type: string
                  format: password
                  minLength: 8
                passwordConfirmation:
                  description: Repeated password from the `password` property
                  type: string
                  format: password
              example:
                fullName: John Smith Doe
                email: johndoe67@gmail.com
                password: 12345678
                passwordConfirmation: 12345678
              required:
                - fullName
                - email
                - password
                - passwordConfirmation
      responses:
        "201":
          description: Success Sign up Request
          content:
            application/json:
              schema:
                type: object
                required:
                  - token
                properties:
                  token:
                    type: string
                    description: JSON Web Token generated from provided resource
              example:
                token: eyJhbGciOiJIUzI1N.eyJzdWIiOiIxMjM0NTY3ODkwIiw.SflKxwRJSMeKKF2QT4fwp
        "403":
          description: User already authenticated and JSON Web Token is still valid
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GeneralError"
              example:
                code: 403
                message: Action forbidden, already authenticated
  /auth/login:
    post:
      tags:
        - authentication
      operationId: userLogIn
      summary: User Logging in
      description: Validate Identity and Generate JSON Web Token
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  description: User Email
                  type: string
                  format: email
                password:
                  description: User Password that should be at least 8 characters long
                  type: string
                  format: password
                  minLength: 8
              example:
                email: johndoe67@gmail.com
                password: 12345678
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  description: User Email
                  type: string
                  format: email
                password:
                  description: User Password that should at least 8 characters long
                  type: string
                  format: password
                  minLength: 8
              example:
                fullName: John Smith Doe
                email: johndoe67@gmail.com
                password: 12345678
                passwordConfirmation: 12345678
      responses:
        "200":
          description: Success Log in Attempt
          content:
            application/json:
              schema:
                type: object
                required:
                  - token
                properties:
                  token:
                    type: string
                    description: JSON Web Token generated from provided resource
              example:
                token: eyJhbGciOiJIUzI1N.eyJzdWIiOiIxMjM0NTY3ODkwIiw.SflKxwRJSMeKKF2QT4fwp
        "401":
          description: Incorrect or fraud credential
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GeneralError"
              example:
                code: 401
                message: Invalid credential
        "403":
          description: User already authenticated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GeneralError"
              example:
                code: 403
                message: Action forbidden, already authenticated
  /user/profile:
    get:
      tags:
        - social-media
      operationId: fetchUserResource
      summary: Fetch User Information (Profile)
      description: Fetch User Information associated from the JSON Web Token
      security:
        - JWTAuth: []
      responses:
        "200":
          description: Successful Fetch User Info Request
          content:
            application/json:
              schema:
                type: object
                required:
                  - user
                properties:
                  user:
                    $ref: "#/components/schemas/User"
                    description: User Resource
                    required:
                      - profilePicture
                      - fullName
                      - email
                      - createdAt
                      - updatedAt
              example:
                user:
                  profilePicture: https://example.com/foo.png
                  fullName: Handedius Sando Sianipar
                  email: sando67@gmail.com
                  createdAt: 2038-01-19 03:14:07
                  updatedAt: 2038-01-19 03:14:07
        "401":
          description: Request Unauthorized. Perhaps JWT Expired or Fraud
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GeneralError"
              example:
                code: 401
                message: Unauthorized
        "404":
          description: Cannot find corresponding User Resource
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GeneralError"
              example:
                code: 404
                message: User not found
    patch:
      tags:
        - social-media
      operationId: patchUserResource
      summary: Update User Information
      description: Update User Resource from the associated JWT
      security:
        - JWTAuth: []
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                profilePicture:
                  type: string
                  contentMediaType: image/png
                  contentEncoding: base64
            example:
              profilePicture: picture.png
          application/json:
            schema:
              type: object
              properties:
                profilePicture:
                  type: string
                  contentMediaType: image/png
                  contentEncoding: base64
            example:
              profilePicture: picture.png
      responses:
        "200":
          description: Successful User Resource Patch
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/APIResponse"
              example:
                code: 200
                message: Resource Patched
        "401":
          description: Request Unauthorized. Perhaps JWT Expired or Fraud
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GeneralError"
              example:
                code: 401
                message: Unauthorized
  /feed:
    get:
      tags:
        - social-media
      operationId: fetchFeed
      summary: Fetch Feed
      description: |-
        Fetch set of Post (Feed) that are close to what user preferred 
        based on user activities
      security:
        - JWTAuth: []
      parameters:
        - name: anchor
          in: query
          description: |-
            A Value taken from last post item createdAt property
            that used as a cursor for pagination
          required: false
          schema:
            type: string
            description: DateTime value taken from CreatedAt property
            format: date-time
            example: 2038-01-19 03:14:07
      responses:
        "200":
          description: Successful Fetch Feed Request
          content:
            application/json:
              schema:
                type: object
                required:
                  - posts
                properties:
                  posts:
                    type: array
                    items:
                      $ref: "#/components/schemas/PlantPost"
        "204":
          description: There is no resource anymore to fetch
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/APIResponse"
              example:
                code: 204
                message: No More Resource
        "401":
          description: Request Unauthorized. Perhaps JWT Expired or Fraud
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GeneralError"
              example:
                code: 401
                message: Unauthorized
components:
  schemas:
    GeneralError:
      type: object
      required:
        - code
      properties:
        code:
          type: integer
          description: HTTP Response Status Code for the Error
          format: int32
          example: [401]
        message:
          type: string
          description: |-
            The Error Response Message. 
            Defaults to the HTTP Response Status Code Message
          example: Unauthorized
        errors:
          type: array
          items:
            type: object
            properties:
              parameter:
                type: string
                description: The Parameter Name thats causing the Error
                example: passwordConfirmation
              message:
                type: string
                description: The Error Message of the corresponding Parameter
                example: Password Confirmation must be the same as the specified Password
    APIResponse:
      type: object
      properties:
        code:
          type: integer
          description: |-
            HTTP Response Status Code for the Response. 
            Ideally this schema will always be used for a Successful Request
          format: int32
          example: 200
        message:
          type: string
          description: |-
            The API Response Message. 
            Defaults to the HTTP Response Status Code Message
          example: OK
    User:
      type: object
      properties:
        id:
          type: string
          minLength: 26
          maxLength: 26
          example: 01HK6TQA7V75K1D4QS6CDK7PXY
        fullName:
          type: string
          example: John Doe
        email:
          type: string
          format: email
          example: johndoe67@gmail.com
        password:
          type: string
          format: password
          example: $2a$12$Zf7NuWW8WaI.ECAiQcenSux.pc1KecPmd/io0rwJ5I4azvh1CMftC
        profilePicture:
          type: string
          description: Picture Image Path or URL
          example: https://example.com/foo.png
        createdAt:
          type: string
          format: date-time
          example: 2038-01-19 03:14:07
        updatedAt:
          type: string
          format: date-time
          example: 2038-01-19 03:14:07
    PlantPost:
      type: object
      properties:
        id:
          type: string
          minLength: 26
          maxLength: 26
          example: 01HK6TQA7V75K1D4QS6CDK7PXY
        picture:
          type: string
          description: Picture Image Path or URL
          example: https://example.com/foo.png
        type:
          type: string
          description: Plant types or common name
          example: Orange
        age:
          type: integer
          description: Plant Age
          format: int32
          example: 4
        description:
          type: string
          description: The correlated plant post description
          example: Fresh oranges we harvest this morning 🍊🌿
        latitude:
          type: number
          description: Latitude value of the location geo coordinate
          format: double
          example: 38.8951
        longitude:
          type: number
          description: Longitude value of the location geo coordinate
          format: double
          example: 38.8951
        createdAt:
          type: string
          format: date-time
          example: 2038-01-19 03:14:07
        updatedAt:
          type: string
          format: date-time
          example: 2038-01-19 03:14:07
  securitySchemes:
    JWTAuth:
      type: http
      description: Authorization and authentication based on JSON Web Token
      scheme: bearer
      bearerFormat: JWT
